In [5]:
import pandas as pd

# part1

### exe1

In [9]:
# size = 10000
# df = pd.read_csv(r'logs.txt.csv', chunksize = size , header=None)

In [1]:
from collections import Counter

def read_lines_in_chunks(file, lines_per_chunk=10000):
    chunk = []
    for line in file:
        chunk.append(line.strip())
        if len(chunk) >= lines_per_chunk:
            yield chunk
            chunk = []
    if chunk:
        yield chunk

chunk_counts = []

def process_data(chunk):
    error_counts = dict(Counter(chunk))
    chunk_counts.append(error_counts)

with open("logs.txt", "r", encoding="utf-8") as f:
    for chunk in read_lines_in_chunks(f):
        process_data(chunk)

### exe2

In [2]:

for i, counts in enumerate(chunk_counts):  
    print(f'Chunk {i+1}:') 
    for key, value in counts.items():
        error = key.split("Error: ")[-1].split('"')[0]  
        print(f'  Error: {error}, Count: {value}')

Chunk 1:
  Error: ERR_400, Count: 2012
  Error: ERR_500, Count: 2015
  Error: INFO_200, Count: 2004
  Error: WARN_101, Count: 1999
  Error: ERR_404, Count: 1970
Chunk 2:
  Error: WARN_101, Count: 2006
  Error: INFO_200, Count: 1994
  Error: ERR_500, Count: 1995
  Error: ERR_404, Count: 2025
  Error: ERR_400, Count: 1980
Chunk 3:
  Error: ERR_404, Count: 2003
  Error: ERR_500, Count: 1940
  Error: INFO_200, Count: 1969
  Error: WARN_101, Count: 2089
  Error: ERR_400, Count: 1999
Chunk 4:
  Error: WARN_101, Count: 1995
  Error: ERR_404, Count: 2048
  Error: ERR_400, Count: 1991
  Error: INFO_200, Count: 2026
  Error: ERR_500, Count: 1940
Chunk 5:
  Error: ERR_500, Count: 1930
  Error: ERR_404, Count: 2029
  Error: WARN_101, Count: 1978
  Error: INFO_200, Count: 2022
  Error: ERR_400, Count: 2041
Chunk 6:
  Error: WARN_101, Count: 1935
  Error: ERR_404, Count: 2048
  Error: ERR_500, Count: 2060
  Error: ERR_400, Count: 2005
  Error: INFO_200, Count: 1952
Chunk 7:
  Error: ERR_404, Count: 2043
  Error: WARN_101, Count: 1990
  Error: ERR_500, Count: 1985
  Error: INFO_200, Count: 1990
  Error: ERR_400, Count: 1992
Chunk 8:
  Error: INFO_200, Count: 1987
  Error: ERR_404, Count: 1986
  Error: ERR_500, Count: 1983
  Error: WARN_101, Count: 2033
  Error: ERR_400, Count: 2011
Chunk 9:
  Error: ERR_404, Count: 2054
  Error: INFO_200, Count: 1963
  Error: ERR_500, Count: 1958
  Error: WARN_101, Count: 2040
  Error: ERR_400, Count: 1985
Chunk 10:
  Error: WARN_101, Count: 1993
  Error: INFO_200, Count: 2020
  Error: ERR_404, Count: 2001
  Error: ERR_400, Count: 1976
  Error: ERR_500, Count: 2010
Chunk 11:
  Error: WARN_101, Count: 2019
  Error: INFO_200, Count: 1970
  Error: ERR_500, Count: 2054
  Error: ERR_404, Count: 2007
  Error: ERR_400, Count: 1950
Chunk 12:
  Error: ERR_500, Count: 1950
  Error: ERR_404, Count: 2010
  Error: INFO_200, Count: 1993
  Error: ERR_400, Count: 2036
  Error: WARN_101, Count: 2011
Chunk 13:
  Error: WARN_101, Count: 2037
  Error: INFO_200, Count: 2059
  Error: ERR_400, Count: 1933
  Error: ERR_500, Count: 2024
  Error: ERR_404, Count: 1947
Chunk 14:
  Error: ERR_404, Count: 2052
  Error: ERR_400, Count: 2011
  Error: ERR_500, Count: 1969
  Error: INFO_200, Count: 1918
  Error: WARN_101, Count: 2050
Chunk 15:
  Error: WARN_101, Count: 2005
  Error: ERR_404, Count: 2017
  Error: INFO_200, Count: 2032
  Error: ERR_500, Count: 1987
  Error: ERR_400, Count: 1959
Chunk 16:
  Error: ERR_404, Count: 2004
  Error: ERR_400, Count: 1970
  Error: ERR_500, Count: 1961
  Error: WARN_101, Count: 2017
  Error: INFO_200, Count: 2048
Chunk 17:
  Error: ERR_500, Count: 2027
  Error: INFO_200, Count: 1997
  Error: ERR_404, Count: 2028
  Error: ERR_400, Count: 1959
  Error: WARN_101, Count: 1989
Chunk 18:
  Error: WARN_101, Count: 1994
  Error: ERR_500, Count: 2018
  Error: ERR_400, Count: 1974
  Error: INFO_200, Count: 2036
  Error: ERR_404, Count: 1978
Chunk 19:
  Error: ERR_404, Count: 2019
  Error: WARN_101, Count: 1958
  Error: ERR_400, Count: 2015
  Error: INFO_200, Count: 1997
  Error: ERR_500, Count: 2011
Chunk 20:
  Error: WARN_101, Count: 2001
  Error: ERR_400, Count: 1897
  Error: ERR_500, Count: 2017
  Error: ERR_404, Count: 2048
  Error: INFO_200, Count: 2037
Chunk 21:
  Error: ERR_400, Count: 2013
  Error: WARN_101, Count: 2038
  Error: ERR_500, Count: 2011
  Error: INFO_200, Count: 1955
  Error: ERR_404, Count: 1983
Chunk 22:
  Error: ERR_400, Count: 2044
  Error: INFO_200, Count: 2003
  Error: WARN_101, Count: 1980
  Error: ERR_500, Count: 2021
  Error: ERR_404, Count: 1952
Chunk 23:
  Error: ERR_404, Count: 2023
  Error: WARN_101, Count: 2012
  Error: ERR_400, Count: 1977
  Error: INFO_200, Count: 1970
  Error: ERR_500, Count: 2018
Chunk 24:
  Error: WARN_101, Count: 2044
  Error: ERR_500, Count: 1950
  Error: ERR_404, Count: 1878
  Error: ERR_400, Count: 2063
  Error: INFO_200, Count: 2065
Chunk 25:
  Error: INFO_200, Count: 2037
  Error: ERR_400, Count: 1952
  Error: WARN_101, Count: 2037
  Error: ERR_404, Count: 1976
  Error: ERR_500, Count: 1998
Chunk 26:
  Error: INFO_200, Count: 2087
  Error: ERR_400, Count: 1955
  Error: WARN_101, Count: 1993
  Error: ERR_404, Count: 1996
  Error: ERR_500, Count: 1969
Chunk 27:
  Error: INFO_200, Count: 1971
  Error: ERR_404, Count: 1951
  Error: WARN_101, Count: 2057
  Error: ERR_500, Count: 2016
  Error: ERR_400, Count: 2005
Chunk 28:
  Error: ERR_500, Count: 1994
  Error: ERR_404, Count: 2012
  Error: ERR_400, Count: 2030
  Error: INFO_200, Count: 1976
  Error: WARN_101, Count: 1988
Chunk 29:
  Error: WARN_101, Count: 2021
  Error: ERR_400, Count: 2017
  Error: ERR_404, Count: 1899
  Error: ERR_500, Count: 2062
  Error: INFO_200, Count: 2001
Chunk 30:
  Error: ERR_400, Count: 2031
  Error: ERR_500, Count: 1980
  Error: ERR_404, Count: 1963
  Error: INFO_200, Count: 1977
  Error: WARN_101, Count: 2049
Chunk 31:
  Error: WARN_101, Count: 2033
  Error: ERR_404, Count: 2068
  Error: ERR_500, Count: 1951
  Error: INFO_200, Count: 1937
  Error: ERR_400, Count: 2011
Chunk 32:
  Error: ERR_500, Count: 1976
  Error: INFO_200, Count: 2003
  Error: ERR_404, Count: 2027
  Error: WARN_101, Count: 2059
  Error: ERR_400, Count: 1935
Chunk 33:
  Error: WARN_101, Count: 2018
  Error: ERR_404, Count: 1968
  Error: INFO_200, Count: 1979
  Error: ERR_500, Count: 2039
  Error: ERR_400, Count: 1996
Chunk 34:
  Error: ERR_404, Count: 2004
  Error: WARN_101, Count: 1969
  Error: ERR_500, Count: 1968
  Error: ERR_400, Count: 2049
  Error: INFO_200, Count: 2010
Chunk 35:
  Error: INFO_200, Count: 2018
  Error: ERR_500, Count: 2044
  Error: ERR_400, Count: 2003
  Error: ERR_404, Count: 1917
  Error: WARN_101, Count: 2018
Chunk 36:
  Error: INFO_200, Count: 2008
  Error: WARN_101, Count: 1985
  Error: ERR_404, Count: 2027
  Error: ERR_500, Count: 2009
  Error: ERR_400, Count: 1971
Chunk 37:
  Error: INFO_200, Count: 1979
  Error: ERR_404, Count: 2026
  Error: WARN_101, Count: 1963
  Error: ERR_400, Count: 2034
  Error: ERR_500, Count: 1998
Chunk 38:
  Error: ERR_400, Count: 1922
  Error: WARN_101, Count: 2079
  Error: ERR_404, Count: 1987
  Error: ERR_500, Count: 2042
  Error: INFO_200, Count: 1970
Chunk 39:
  Error: ERR_400, Count: 2017
  Error: ERR_404, Count: 2009
  Error: WARN_101, Count: 1945
  Error: ERR_500, Count: 2028
  Error: INFO_200, Count: 2001
Chunk 40:
  Error: ERR_404, Count: 2028
  Error: WARN_101, Count: 1985
  Error: ERR_500, Count: 1954
  Error: ERR_400, Count: 1979
  Error: INFO_200, Count: 2054
Chunk 41:
  Error: ERR_400, Count: 1956
  Error: ERR_500, Count: 2058
  Error: INFO_200, Count: 2008
  Error: WARN_101, Count: 1916
  Error: ERR_404, Count: 2062
Chunk 42:
  Error: INFO_200, Count: 2047
  Error: ERR_400, Count: 1987
  Error: ERR_404, Count: 1994
  Error: WARN_101, Count: 2038
  Error: ERR_500, Count: 1934
Chunk 43:
  Error: ERR_400, Count: 1993
  Error: ERR_500, Count: 2024
  Error: WARN_101, Count: 2060
  Error: ERR_404, Count: 1967
  Error: INFO_200, Count: 1956
Chunk 44:
  Error: ERR_400, Count: 1957
  Error: WARN_101, Count: 2011
  Error: INFO_200, Count: 1990
  Error: ERR_404, Count: 2044
  Error: ERR_500, Count: 1998
Chunk 45:
  Error: INFO_200, Count: 2012
  Error: ERR_400, Count: 2015
  Error: ERR_500, Count: 2020
  Error: WARN_101, Count: 2045
  Error: ERR_404, Count: 1908
Chunk 46:
  Error: ERR_404, Count: 2036
  Error: WARN_101, Count: 2058
  Error: ERR_500, Count: 1971
  Error: ERR_400, Count: 1953
  Error: INFO_200, Count: 1982
Chunk 47:
  Error: WARN_101, Count: 1991
  Error: ERR_500, Count: 1991
  Error: ERR_404, Count: 2045
  Error: ERR_400, Count: 2026
  Error: INFO_200, Count: 1947
Chunk 48:
  Error: WARN_101, Count: 2056
  Error: ERR_500, Count: 2001
  Error: INFO_200, Count: 2019
  Error: ERR_404, Count: 1953
  Error: ERR_400, Count: 1971
Chunk 49:
  Error: ERR_404, Count: 1989
  Error: WARN_101, Count: 1943
  Error: ERR_500, Count: 2071
  Error: ERR_400, Count: 2008
  Error: INFO_200, Count: 1989
Chunk 50:
  Error: INFO_200, Count: 2038
  Error: ERR_400, Count: 1944
  Error: ERR_404, Count: 1998
  Error: WARN_101, Count: 1971
  Error: ERR_500, Count: 2049
Chunk 51:
  Error: ERR_400, Count: 2009
  Error: WARN_101, Count: 2029
  Error: ERR_404, Count: 1996
  Error: INFO_200, Count: 2005
  Error: ERR_500, Count: 1961
Chunk 52:
  Error: INFO_200, Count: 2008
  Error: ERR_500, Count: 1950
  Error: ERR_404, Count: 1991
  Error: WARN_101, Count: 2004
  Error: ERR_400, Count: 2047
Chunk 53:
  Error: ERR_500, Count: 2024
  Error: ERR_400, Count: 2021
  Error: INFO_200, Count: 1990
  Error: ERR_404, Count: 2004
  Error: WARN_101, Count: 1961
Chunk 54:
  Error: INFO_200, Count: 1928
  Error: ERR_404, Count: 2007
  Error: ERR_400, Count: 2057
  Error: WARN_101, Count: 1931
  Error: ERR_500, Count: 2077
Chunk 55:
  Error: INFO_200, Count: 2064
  Error: ERR_400, Count: 2001
  Error: ERR_404, Count: 1972
  Error: WARN_101, Count: 1946
  Error: ERR_500, Count: 2017
Chunk 56:
  Error: ERR_400, Count: 2062
  Error: WARN_101, Count: 1907
  Error: INFO_200, Count: 2056
  Error: ERR_500, Count: 1965
  Error: ERR_404, Count: 2010
Chunk 57:
  Error: ERR_500, Count: 1993
  Error: ERR_404, Count: 2063
  Error: ERR_400, Count: 1920
  Error: WARN_101, Count: 2015
  Error: INFO_200, Count: 2009
Chunk 58:
  Error: ERR_500, Count: 2037
  Error: INFO_200, Count: 1985
  Error: ERR_404, Count: 1943
  Error: ERR_400, Count: 2043
  Error: WARN_101, Count: 1992
Chunk 59:
  Error: ERR_400, Count: 2024
  Error: ERR_404, Count: 2008
  Error: ERR_500, Count: 1962
  Error: WARN_101, Count: 1973
  Error: INFO_200, Count: 2033
Chunk 60:
  Error: ERR_404, Count: 1990
  Error: ERR_400, Count: 2031
  Error: ERR_500, Count: 2007
  Error: INFO_200, Count: 1991
  Error: WARN_101, Count: 1981
Chunk 61:
  Error: ERR_404, Count: 2026
  Error: INFO_200, Count: 1995
  Error: ERR_500, Count: 2002
  Error: WARN_101, Count: 1985
  Error: ERR_400, Count: 1992
Chunk 62:
  Error: ERR_400, Count: 2004
  Error: WARN_101, Count: 1997
  Error: ERR_404, Count: 2015
  Error: INFO_200, Count: 1980
  Error: ERR_500, Count: 2004
Chunk 63:
  Error: ERR_404, Count: 2014
  Error: ERR_400, Count: 1981
  Error: ERR_500, Count: 2029
  Error: INFO_200, Count: 1958
  Error: WARN_101, Count: 2018
Chunk 64:
  Error: INFO_200, Count: 2051
  Error: ERR_400, Count: 2005
  Error: ERR_500, Count: 1964
  Error: WARN_101, Count: 2012
  Error: ERR_404, Count: 1968
Chunk 65:
  Error: INFO_200, Count: 1981
  Error: WARN_101, Count: 1960
  Error: ERR_404, Count: 2080
  Error: ERR_400, Count: 1984
  Error: ERR_500, Count: 1995
Chunk 66:
  Error: ERR_500, Count: 2038
  Error: ERR_404, Count: 1956
  Error: ERR_400, Count: 2054
  Error: INFO_200, Count: 1997
  Error: WARN_101, Count: 1955
Chunk 67:
  Error: ERR_400, Count: 2044
  Error: INFO_200, Count: 1972
  Error: ERR_500, Count: 1965
  Error: ERR_404, Count: 1986
  Error: WARN_101, Count: 2033
Chunk 68:
  Error: INFO_200, Count: 1964
  Error: ERR_400, Count: 2033
  Error: WARN_101, Count: 1988
  Error: ERR_404, Count: 2042
  Error: ERR_500, Count: 1973
Chunk 69:
  Error: INFO_200, Count: 2011
  Error: ERR_400, Count: 2069
  Error: WARN_101, Count: 1944
  Error: ERR_500, Count: 2011
  Error: ERR_404, Count: 1965
Chunk 70:
  Error: WARN_101, Count: 1950
  Error: ERR_404, Count: 2059
  Error: INFO_200, Count: 2049
  Error: ERR_500, Count: 2001
  Error: ERR_400, Count: 1941
Chunk 71:
  Error: ERR_400, Count: 1963
  Error: WARN_101, Count: 2073
  Error: INFO_200, Count: 2014
  Error: ERR_404, Count: 1988
  Error: ERR_500, Count: 1962
Chunk 72:
  Error: ERR_404, Count: 2031
  Error: ERR_400, Count: 1990
  Error: ERR_500, Count: 1998
  Error: INFO_200, Count: 2023
  Error: WARN_101, Count: 1958
Chunk 73:
  Error: ERR_404, Count: 2038
  Error: WARN_101, Count: 1969
  Error: INFO_200, Count: 1942
  Error: ERR_500, Count: 2018
  Error: ERR_400, Count: 2033
Chunk 74:
  Error: ERR_400, Count: 1990
  Error: INFO_200, Count: 2031
  Error: WARN_101, Count: 2004
  Error: ERR_404, Count: 2005
  Error: ERR_500, Count: 1970
Chunk 75:
  Error: ERR_404, Count: 2012
  Error: WARN_101, Count: 2040
  Error: INFO_200, Count: 1981
  Error: ERR_400, Count: 2018
  Error: ERR_500, Count: 1949
Chunk 76:
  Error: ERR_404, Count: 1953
  Error: WARN_101, Count: 2045
  Error: ERR_400, Count: 2072
  Error: ERR_500, Count: 1947
  Error: INFO_200, Count: 1983
Chunk 77:
  Error: ERR_400, Count: 2000
  Error: ERR_404, Count: 1992
  Error: ERR_500, Count: 2001
  Error: INFO_200, Count: 2021
  Error: WARN_101, Count: 1986
Chunk 78:
  Error: ERR_404, Count: 1969
  Error: ERR_400, Count: 1966
  Error: WARN_101, Count: 1964
  Error: INFO_200, Count: 2013
  Error: ERR_500, Count: 2088
Chunk 79:
  Error: ERR_400, Count: 2085
  Error: WARN_101, Count: 2036
  Error: ERR_500, Count: 1963
  Error: ERR_404, Count: 1978
  Error: INFO_200, Count: 1938
Chunk 80:
  Error: INFO_200, Count: 2007
  Error: ERR_404, Count: 1963
  Error: ERR_500, Count: 2018
  Error: WARN_101, Count: 2033
  Error: ERR_400, Count: 1979
Chunk 81:
  Error: ERR_400, Count: 2005
  Error: WARN_101, Count: 1999
  Error: INFO_200, Count: 2009
  Error: ERR_500, Count: 1961
  Error: ERR_404, Count: 2026
Chunk 82:
  Error: ERR_500, Count: 1990
  Error: INFO_200, Count: 1979
  Error: ERR_400, Count: 1975
  Error: ERR_404, Count: 2005
  Error: WARN_101, Count: 2051
Chunk 83:
  Error: ERR_500, Count: 1959
  Error: INFO_200, Count: 2052
  Error: WARN_101, Count: 1942
  Error: ERR_400, Count: 2021
  Error: ERR_404, Count: 2026
Chunk 84:
  Error: ERR_404, Count: 1995
  Error: ERR_500, Count: 1943
  Error: INFO_200, Count: 2047
  Error: ERR_400, Count: 2004
  Error: WARN_101, Count: 2011
Chunk 85:
  Error: WARN_101, Count: 2008
  Error: ERR_400, Count: 1987
  Error: ERR_404, Count: 2003
  Error: ERR_500, Count: 1977
  Error: INFO_200, Count: 2025
Chunk 86:
  Error: WARN_101, Count: 2063
  Error: ERR_500, Count: 1922
  Error: ERR_400, Count: 2021
  Error: ERR_404, Count: 2006
  Error: INFO_200, Count: 1988
Chunk 87:
  Error: INFO_200, Count: 2051
  Error: ERR_404, Count: 1952
  Error: ERR_500, Count: 2032
  Error: ERR_400, Count: 2002
  Error: WARN_101, Count: 1963
Chunk 88:
  Error: ERR_400, Count: 2087
  Error: ERR_404, Count: 1985
  Error: ERR_500, Count: 2001
  Error: INFO_200, Count: 2005
  Error: WARN_101, Count: 1922
Chunk 89:
  Error: WARN_101, Count: 2021
  Error: INFO_200, Count: 1951
  Error: ERR_500, Count: 1969
  Error: ERR_400, Count: 2035
  Error: ERR_404, Count: 2024
Chunk 90:
  Error: ERR_500, Count: 1984
  Error: ERR_400, Count: 1969
  Error: INFO_200, Count: 2059
  Error: WARN_101, Count: 1948
  Error: ERR_404, Count: 2040
Chunk 91:
  Error: ERR_404, Count: 2076
  Error: ERR_400, Count: 1952
  Error: ERR_500, Count: 2006
  Error: INFO_200, Count: 1993
  Error: WARN_101, Count: 1973
Chunk 92:
  Error: ERR_500, Count: 2059
  Error: INFO_200, Count: 2030
  Error: ERR_400, Count: 1947
  Error: ERR_404, Count: 1975
  Error: WARN_101, Count: 1989
Chunk 93:
  Error: ERR_500, Count: 2024
  Error: ERR_404, Count: 2030
  Error: INFO_200, Count: 1987
  Error: ERR_400, Count: 1953
  Error: WARN_101, Count: 2006
Chunk 94:
  Error: INFO_200, Count: 1952
  Error: WARN_101, Count: 2021
  Error: ERR_500, Count: 2030
  Error: ERR_400, Count: 1979
  Error: ERR_404, Count: 2018
Chunk 95:
  Error: ERR_404, Count: 1979
  Error: ERR_400, Count: 2002
  Error: INFO_200, Count: 1984
  Error: WARN_101, Count: 2006
  Error: ERR_500, Count: 2029
Chunk 96:
  Error: INFO_200, Count: 1998
  Error: WARN_101, Count: 2009
  Error: ERR_500, Count: 1936
  Error: ERR_404, Count: 2038
  Error: ERR_400, Count: 2019
Chunk 97:
  Error: ERR_404, Count: 2011
  Error: INFO_200, Count: 1961
  Error: ERR_500, Count: 2015
  Error: WARN_101, Count: 1996
  Error: ERR_400, Count: 2017
Chunk 98:
  Error: INFO_200, Count: 1989
  Error: ERR_500, Count: 2031
  Error: ERR_404, Count: 1922
  Error: WARN_101, Count: 2007
  Error: ERR_400, Count: 2051
Chunk 99:
  Error: ERR_400, Count: 2042
  Error: ERR_500, Count: 2063
  Error: INFO_200, Count: 1945
  Error: WARN_101, Count: 1990
  Error: ERR_404, Count: 1960
Chunk 100:
  Error: ERR_404, Count: 1992
  Error: INFO_200, Count: 1943
  Error: ERR_500, Count: 2009
  Error: WARN_101, Count: 1983
  Error: ERR_400, Count: 2073

### exe3

In [3]:


total_counts = Counter()


for error_counts in chunk_counts:
    total_counts.update(error_counts)

print("Total Counts:")
for key, value in total_counts.items():
    error = key.split("Error: ")[-1].split('"')[0]  
    print(f'  Error: {error}, Count: {value}')

Total Counts:
  Error: ERR_400, Count: 200069
  Error: ERR_500, Count: 199808
  Error: INFO_200, Count: 199931
  Error: WARN_101, Count: 200098
  Error: ERR_404, Count: 200094

### exe4

In [4]:
def findFreq(n):
    top_n = total_counts.most_common(n)
    print(f"{n} common errors:")
    for error, count in top_n:
        print(f" {error.split("Error:")[-1].split('"')[0] }: {count}")
findFreq(3)

3 common errors:
  WARN_101: 200098
  ERR_404: 200094
  ERR_400: 200069

### exe5

#### סיבוכיות הזמן שלי היא:
##### n רשומות , m סוגי שגיאות
##### o(n) לעבור על כל הרשומות ב df 
##### o(n/10000) = o(n) לעבור על כל החלקים ולשמור לכל אחד רשימת שכיחויות
##### o(n/10000) = o(n) למזג את כל הרשימות לרשימה אחת
##### לעבור על רשימת השכיחויות המשותפת ולמיין את השגיאות- במקרה הגרוע שבו m=n הזמן ריצה יהיה o(nlogn) עם שימוש במיון מיזוג
##### להדפיס את N השגיאות הנפוצות ביותר-   o(N)
##### סה"כ זמן הריצה של כל התכנית : o(nlogn) במקרה הגרוע ו o(n) במקרה הטוב

# part2

### exe1

In [16]:

from pathlib import Path
file_path_xlsx = Path(r'time_series.xlsx')
file_path_parquet = Path(r'time_series.parquet')

def open_file(file):
    if file.suffix.lower() == '.xlsx':
        return  pd.read_excel(file)
    elif file.suffix.lower() == '.parquet':
        return pd.read_parquet(file)
        
df = open_file(file_path_parquet)
df

                  timestamp value
0       28/06/2025 12:00:52  18.5
1       01/06/2025 04:17:23  46.3
2       10/06/2025 17:02:57    76
3       23/06/2025 05:23:22  56.4
4       05/06/2025 07:20:08  67.9
...                     ...   ...
999995  21/06/2025 18:41:04  44.8
999996  26/06/2025 21:09:47  None
999997  24/06/2025 18:51:12   3.9
999998  10/06/2025 08:36:18    77
999999  05/06/2025 22:30:46  43.3

[1000000 rows x 2 columns]

In [8]:
df

                  timestamp value
0       28/06/2025 12:00:52  18.5
1       01/06/2025 04:17:23  46.3
2       10/06/2025 17:02:57    76
3       23/06/2025 05:23:22  56.4
4       05/06/2025 07:20:08  67.9
...                     ...   ...
999995  21/06/2025 18:41:04  44.8
999996  26/06/2025 21:09:47  None
999997  24/06/2025 18:51:12   3.9
999998  10/06/2025 08:36:18    77
999999  05/06/2025 22:30:46  43.3

[1000000 rows x 2 columns]

In [17]:

dup = df[df.duplicated()]
if not dup.empty:
    print(dup)
    df=df.drop_duplicates()

                  timestamp         value
16085   12/06/2025 22:31:23          None
26420   05/06/2025 01:39:21          None
39052   10/06/2025 09:54:06          None
40835   05/06/2025 12:07:30          None
49961   03/06/2025 16:20:32  not_a_number
...                     ...           ...
999300  03/06/2025 11:17:22          None
999429  22/06/2025 20:06:07          None
999478  09/06/2025 11:42:30          None
999508  12/06/2025 12:53:11          None
999536  17/06/2025 13:31:50  not_a_number

[2598 rows x 2 columns]

In [18]:
df.loc[:, 'timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

invalid_dates = df[df['timestamp'].isna()]
if not invalid_dates.empty:
    print("there is invalid dates")
    print(invalid_dates)
df = df.dropna(subset=['timestamp'])

C:\Users\User\AppData\Local\Temp\ipykernel_29752\3459205520.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df.loc[:, 'timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

In [19]:
df['value'] = pd.to_numeric(df['value'], errors='coerce')
df['value']=df['value'].fillna(df['value'].mean()) 

df

                  timestamp    value
0       2025-06-28 12:00:52  18.5000
1       2025-06-01 04:17:23  46.3000
2       2025-06-10 17:02:57  76.0000
3       2025-06-23 05:23:22  56.4000
4       2025-06-05 07:20:08  67.9000
...                     ...      ...
999995  2025-06-21 18:41:04  44.8000
999996  2025-06-26 21:09:47  49.9623
999997  2025-06-24 18:51:12   3.9000
999998  2025-06-10 08:36:18  77.0000
999999  2025-06-05 22:30:46  43.3000

[997402 rows x 2 columns]

### exe2.1

In [20]:
df = df.copy()
df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')
df['hour']=df['timestamp'].dt.floor('h')
df

                 timestamp    value                hour
0      2025-06-28 12:00:52  18.5000 2025-06-28 12:00:00
1      2025-06-01 04:17:23  46.3000 2025-06-01 04:00:00
2      2025-06-10 17:02:57  76.0000 2025-06-10 17:00:00
3      2025-06-23 05:23:22  56.4000 2025-06-23 05:00:00
4      2025-06-05 07:20:08  67.9000 2025-06-05 07:00:00
...                    ...      ...                 ...
999995 2025-06-21 18:41:04  44.8000 2025-06-21 18:00:00
999996 2025-06-26 21:09:47  49.9623 2025-06-26 21:00:00
999997 2025-06-24 18:51:12   3.9000 2025-06-24 18:00:00
999998 2025-06-10 08:36:18  77.0000 2025-06-10 08:00:00
999999 2025-06-05 22:30:46  43.3000 2025-06-05 22:00:00

[997402 rows x 3 columns]

In [21]:
df.groupby('hour')['value'].mean().reset_index()

                   hour      value
0   2025-06-01 00:00:00  50.485862
1   2025-06-01 01:00:00  49.942694
2   2025-06-01 02:00:00  49.536653
3   2025-06-01 03:00:00  50.151515
4   2025-06-01 04:00:00  48.806004
..                  ...        ...
715 2025-06-30 19:00:00  50.766593
716 2025-06-30 20:00:00  49.065881
717 2025-06-30 21:00:00  50.657145
718 2025-06-30 22:00:00  48.440872
719 2025-06-30 23:00:00  50.257774

[720 rows x 2 columns]

### exe2.2

In [22]:
df['day'] = df['timestamp'].dt.day  
groups = {day: group for day, group in df.groupby('day')}  


print(groups[1].head())

              timestamp    value                hour  day
1   2025-06-01 04:17:23  46.3000 2025-06-01 04:00:00    1
24  2025-06-01 08:17:54  45.2000 2025-06-01 08:00:00    1
61  2025-06-01 07:59:40  85.5000 2025-06-01 07:00:00    1
69  2025-06-01 09:00:27  49.9623 2025-06-01 09:00:00    1
136 2025-06-01 10:37:19  64.3000 2025-06-01 10:00:00    1

In [23]:
results = []
for g in groups.values():
    results.append(g.groupby('hour')['value'].mean().reset_index())
    
for r in results:
    print(r)

                  hour      value
0  2025-06-01 00:00:00  50.485862
1  2025-06-01 01:00:00  49.942694
2  2025-06-01 02:00:00  49.536653
3  2025-06-01 03:00:00  50.151515
4  2025-06-01 04:00:00  48.806004
5  2025-06-01 05:00:00  50.608675
6  2025-06-01 06:00:00  50.624396
7  2025-06-01 07:00:00  49.406874
8  2025-06-01 08:00:00  49.950761
9  2025-06-01 09:00:00  49.192266
10 2025-06-01 10:00:00  49.177073
11 2025-06-01 11:00:00  48.560263
12 2025-06-01 12:00:00  50.045974
13 2025-06-01 13:00:00  49.893741
14 2025-06-01 14:00:00  49.493415
15 2025-06-01 15:00:00  49.307470
16 2025-06-01 16:00:00  49.884977
17 2025-06-01 17:00:00  51.823176
18 2025-06-01 18:00:00  49.441352
19 2025-06-01 19:00:00  49.839952
20 2025-06-01 20:00:00  49.828947
21 2025-06-01 21:00:00  50.429709
22 2025-06-01 22:00:00  50.059495
23 2025-06-01 23:00:00  49.562508
                  hour      value
0  2025-06-02 00:00:00  51.677878
1  2025-06-02 01:00:00  49.040425
2  2025-06-02 02:00:00  49.711196
3  2025-06-02 03:00:00  51.346955
4  2025-06-02 04:00:00  50.365709
5  2025-06-02 05:00:00  49.748808
6  2025-06-02 06:00:00  50.306615
7  2025-06-02 07:00:00  49.216854
8  2025-06-02 08:00:00  49.132639
9  2025-06-02 09:00:00  49.962622
10 2025-06-02 10:00:00  49.523157
11 2025-06-02 11:00:00  48.954509
12 2025-06-02 12:00:00  48.763521
13 2025-06-02 13:00:00  51.402244
14 2025-06-02 14:00:00  50.427001
15 2025-06-02 15:00:00  50.934597
16 2025-06-02 16:00:00  50.138873
17 2025-06-02 17:00:00  50.186584
18 2025-06-02 18:00:00  50.374646
19 2025-06-02 19:00:00  50.707232
20 2025-06-02 20:00:00  49.832757
21 2025-06-02 21:00:00  51.486600
22 2025-06-02 22:00:00  49.320681
23 2025-06-02 23:00:00  50.205193
                  hour      value
0  2025-06-03 00:00:00  49.712984
1  2025-06-03 01:00:00  49.531060
2  2025-06-03 02:00:00  49.788310
3  2025-06-03 03:00:00  48.243624
4  2025-06-03 04:00:00  49.173207
5  2025-06-03 05:00:00  49.310307
6  2025-06-03 06:00:00  49.614721
7  2025-06-03 07:00:00  50.471143
8  2025-06-03 08:00:00  49.177792
9  2025-06-03 09:00:00  50.851458
10 2025-06-03 10:00:00  49.998863
11 2025-06-03 11:00:00  50.570808
12 2025-06-03 12:00:00  50.112383
13 2025-06-03 13:00:00  49.937001
14 2025-06-03 14:00:00  48.387269
15 2025-06-03 15:00:00  50.197880
16 2025-06-03 16:00:00  49.728619
17 2025-06-03 17:00:00  48.828280
18 2025-06-03 18:00:00  50.095209
19 2025-06-03 19:00:00  50.199819
20 2025-06-03 20:00:00  50.883023
21 2025-06-03 21:00:00  50.613336
22 2025-06-03 22:00:00  49.264198
23 2025-06-03 23:00:00  49.936522
                  hour      value
0  2025-06-04 00:00:00  49.466726
1  2025-06-04 01:00:00  50.955404
2  2025-06-04 02:00:00  50.967489
3  2025-06-04 03:00:00  50.838991
4  2025-06-04 04:00:00  50.217212
5  2025-06-04 05:00:00  50.200383
6  2025-06-04 06:00:00  50.233824
7  2025-06-04 07:00:00  49.558867
8  2025-06-04 08:00:00  49.255083
9  2025-06-04 09:00:00  51.508813
10 2025-06-04 10:00:00  49.601313
11 2025-06-04 11:00:00  50.080815
12 2025-06-04 12:00:00  50.133376
13 2025-06-04 13:00:00  48.701860
14 2025-06-04 14:00:00  48.930991
15 2025-06-04 15:00:00  50.362115
16 2025-06-04 16:00:00  50.258859
17 2025-06-04 17:00:00  50.167244
18 2025-06-04 18:00:00  50.244488
19 2025-06-04 19:00:00  51.009415
20 2025-06-04 20:00:00  50.435227
21 2025-06-04 21:00:00  50.050105
22 2025-06-04 22:00:00  49.926912
23 2025-06-04 23:00:00  48.848411
                  hour      value
0  2025-06-05 00:00:00  48.730102
1  2025-06-05 01:00:00  49.129204
2  2025-06-05 02:00:00  50.558307
3  2025-06-05 03:00:00  50.467103
4  2025-06-05 04:00:00  50.217994
5  2025-06-05 05:00:00  49.721263
6  2025-06-05 06:00:00  49.615546
7  2025-06-05 07:00:00  49.049859
8  2025-06-05 08:00:00  50.275149
9  2025-06-05 09:00:00  49.741924
10 2025-06-05 10:00:00  50.428808
11 2025-06-05 11:00:00  50.360636
12 2025-06-05 12:00:00  50.528124
13 2025-06-05 13:00:00  49.729952
14 2025-06-05 14:00:00  50.698537
15 2025-06-05 15:00:00  49.638999
16 2025-06-05 16:00:00  49.182775
17 2025-06-05 17:00:00  50.277615
18 2025-06-05 18:00:00  50.027158
19 2025-06-05 19:00:00  50.837198
20 2025-06-05 20:00:00  50.128375
21 2025-06-05 21:00:00  49.211289
22 2025-06-05 22:00:00  50.629866
23 2025-06-05 23:00:00  50.000191
                  hour      value
0  2025-06-06 00:00:00  49.087133
1  2025-06-06 01:00:00  50.731934
2  2025-06-06 02:00:00  50.411318
3  2025-06-06 03:00:00  50.017210
4  2025-06-06 04:00:00  50.476193
5  2025-06-06 05:00:00  49.034855
6  2025-06-06 06:00:00  49.116335
7  2025-06-06 07:00:00  49.145941
8  2025-06-06 08:00:00  50.169310
9  2025-06-06 09:00:00  48.893064
10 2025-06-06 10:00:00  51.082413
11 2025-06-06 11:00:00  50.034790
12 2025-06-06 12:00:00  50.537443
13 2025-06-06 13:00:00  50.902885
14 2025-06-06 14:00:00  51.194782
15 2025-06-06 15:00:00  48.856685
16 2025-06-06 16:00:00  49.845956
17 2025-06-06 17:00:00  49.333304
18 2025-06-06 18:00:00  50.243532
19 2025-06-06 19:00:00  49.323623
20 2025-06-06 20:00:00  51.054223
21 2025-06-06 21:00:00  50.069209
22 2025-06-06 22:00:00  49.735438
23 2025-06-06 23:00:00  49.281570
                  hour      value
0  2025-06-07 00:00:00  50.126572
1  2025-06-07 01:00:00  49.885302
2  2025-06-07 02:00:00  49.894201
3  2025-06-07 03:00:00  50.551858
4  2025-06-07 04:00:00  49.977885
5  2025-06-07 05:00:00  49.363337
6  2025-06-07 06:00:00  49.088690
7  2025-06-07 07:00:00  51.380532
8  2025-06-07 08:00:00  50.752410
9  2025-06-07 09:00:00  50.170774
10 2025-06-07 10:00:00  49.156089
11 2025-06-07 11:00:00  49.370942
12 2025-06-07 12:00:00  49.733845
13 2025-06-07 13:00:00  50.086687
14 2025-06-07 14:00:00  49.646136
15 2025-06-07 15:00:00  51.221393
16 2025-06-07 16:00:00  49.608004
17 2025-06-07 17:00:00  50.157352
18 2025-06-07 18:00:00  48.978051
19 2025-06-07 19:00:00  49.369350
20 2025-06-07 20:00:00  50.275168
21 2025-06-07 21:00:00  49.493707
22 2025-06-07 22:00:00  50.078848
23 2025-06-07 23:00:00  49.656746
                  hour      value
0  2025-06-08 00:00:00  49.093638
1  2025-06-08 01:00:00  50.057974
2  2025-06-08 02:00:00  49.986404
3  2025-06-08 03:00:00  50.285113
4  2025-06-08 04:00:00  48.968850
5  2025-06-08 05:00:00  49.274935
6  2025-06-08 06:00:00  48.754223
7  2025-06-08 07:00:00  49.512089
8  2025-06-08 08:00:00  48.674918
9  2025-06-08 09:00:00  49.618490
10 2025-06-08 10:00:00  50.309563
11 2025-06-08 11:00:00  51.751166
12 2025-06-08 12:00:00  49.805655
13 2025-06-08 13:00:00  50.735628
14 2025-06-08 14:00:00  50.533724
15 2025-06-08 15:00:00  50.061230
16 2025-06-08 16:00:00  49.678052
17 2025-06-08 17:00:00  49.827438
18 2025-06-08 18:00:00  50.639529
19 2025-06-08 19:00:00  51.088490
20 2025-06-08 20:00:00  47.721376
21 2025-06-08 21:00:00  49.978713
22 2025-06-08 22:00:00  50.461965
23 2025-06-08 23:00:00  50.272737
                  hour      value
0  2025-06-09 00:00:00  48.831669
1  2025-06-09 01:00:00  49.482646
2  2025-06-09 02:00:00  48.592611
3  2025-06-09 03:00:00  49.609544
4  2025-06-09 04:00:00  49.539964
5  2025-06-09 05:00:00  49.406541
6  2025-06-09 06:00:00  49.478885
7  2025-06-09 07:00:00  50.826091
8  2025-06-09 08:00:00  48.824702
9  2025-06-09 09:00:00  50.824804
10 2025-06-09 10:00:00  50.641115
11 2025-06-09 11:00:00  49.169974
12 2025-06-09 12:00:00  49.541787
13 2025-06-09 13:00:00  49.170148
14 2025-06-09 14:00:00  50.251042
15 2025-06-09 15:00:00  50.455455
16 2025-06-09 16:00:00  49.803379
17 2025-06-09 17:00:00  49.305607
18 2025-06-09 18:00:00  50.593468
19 2025-06-09 19:00:00  49.940988
20 2025-06-09 20:00:00  51.679236
21 2025-06-09 21:00:00  50.128755
22 2025-06-09 22:00:00  49.516426
23 2025-06-09 23:00:00  47.967451
                  hour      value
0  2025-06-10 00:00:00  49.215413
1  2025-06-10 01:00:00  49.610963
2  2025-06-10 02:00:00  50.879907
3  2025-06-10 03:00:00  50.173912
4  2025-06-10 04:00:00  49.845106
5  2025-06-10 05:00:00  49.301764
6  2025-06-10 06:00:00  50.477835
7  2025-06-10 07:00:00  50.435758
8  2025-06-10 08:00:00  50.494782
9  2025-06-10 09:00:00  49.557378
10 2025-06-10 10:00:00  50.186574
11 2025-06-10 11:00:00  50.518398
12 2025-06-10 12:00:00  50.173619
13 2025-06-10 13:00:00  50.388288
14 2025-06-10 14:00:00  50.635204
15 2025-06-10 15:00:00  50.005476
16 2025-06-10 16:00:00  50.182204
17 2025-06-10 17:00:00  49.540639
18 2025-06-10 18:00:00  49.993609
19 2025-06-10 19:00:00  49.792568
20 2025-06-10 20:00:00  50.296854
21 2025-06-10 21:00:00  49.347414
22 2025-06-10 22:00:00  50.244508
23 2025-06-10 23:00:00  49.841406
                  hour      value
0  2025-06-11 00:00:00  48.119076
1  2025-06-11 01:00:00  49.394668
2  2025-06-11 02:00:00  50.716772
3  2025-06-11 03:00:00  50.588329
4  2025-06-11 04:00:00  51.158302
5  2025-06-11 05:00:00  50.110861
6  2025-06-11 06:00:00  49.942399
7  2025-06-11 07:00:00  50.199154
8  2025-06-11 08:00:00  49.583952
9  2025-06-11 09:00:00  50.301484
10 2025-06-11 10:00:00  49.720567
11 2025-06-11 11:00:00  49.726776
12 2025-06-11 12:00:00  49.095495
13 2025-06-11 13:00:00  48.666033
14 2025-06-11 14:00:00  49.706830
15 2025-06-11 15:00:00  48.939171
16 2025-06-11 16:00:00  49.019029
17 2025-06-11 17:00:00  50.702673
18 2025-06-11 18:00:00  50.563343
19 2025-06-11 19:00:00  49.500914
20 2025-06-11 20:00:00  50.470009
21 2025-06-11 21:00:00  49.838221
22 2025-06-11 22:00:00  49.300715
23 2025-06-11 23:00:00  49.776456
                  hour      value
0  2025-06-12 00:00:00  50.205458
1  2025-06-12 01:00:00  50.747318
2  2025-06-12 02:00:00  48.317674
3  2025-06-12 03:00:00  48.329332
4  2025-06-12 04:00:00  49.682803
5  2025-06-12 05:00:00  49.171224
6  2025-06-12 06:00:00  50.628346
7  2025-06-12 07:00:00  50.302075
8  2025-06-12 08:00:00  48.734771
9  2025-06-12 09:00:00  50.203917
10 2025-06-12 10:00:00  49.626427
11 2025-06-12 11:00:00  50.401155
12 2025-06-12 12:00:00  49.895416
13 2025-06-12 13:00:00  50.327695
14 2025-06-12 14:00:00  49.719771
15 2025-06-12 15:00:00  49.958785
16 2025-06-12 16:00:00  49.825982
17 2025-06-12 17:00:00  49.295743
18 2025-06-12 18:00:00  48.680085
19 2025-06-12 19:00:00  48.438208
20 2025-06-12 20:00:00  49.970110
21 2025-06-12 21:00:00  49.448601
22 2025-06-12 22:00:00  50.581397
23 2025-06-12 23:00:00  49.894356
                  hour      value
0  2025-06-13 00:00:00  48.544128
1  2025-06-13 01:00:00  49.931177
2  2025-06-13 02:00:00  50.148812
3  2025-06-13 03:00:00  50.147164
4  2025-06-13 04:00:00  50.205646
5  2025-06-13 05:00:00  49.807338
6  2025-06-13 06:00:00  49.764685
7  2025-06-13 07:00:00  50.182419
8  2025-06-13 08:00:00  50.909777
9  2025-06-13 09:00:00  49.200320
10 2025-06-13 10:00:00  49.843944
11 2025-06-13 11:00:00  50.820585
12 2025-06-13 12:00:00  50.663660
13 2025-06-13 13:00:00  50.125411
14 2025-06-13 14:00:00  49.818722
15 2025-06-13 15:00:00  50.971098
16 2025-06-13 16:00:00  49.980982
17 2025-06-13 17:00:00  51.317979
18 2025-06-13 18:00:00  49.335572
19 2025-06-13 19:00:00  50.207714
20 2025-06-13 20:00:00  49.335013
21 2025-06-13 21:00:00  48.740309
22 2025-06-13 22:00:00  49.055702
23 2025-06-13 23:00:00  49.614382
                  hour      value
0  2025-06-14 00:00:00  50.193870
1  2025-06-14 01:00:00  50.191073
2  2025-06-14 02:00:00  49.952533
3  2025-06-14 03:00:00  49.623334
4  2025-06-14 04:00:00  50.443744
5  2025-06-14 05:00:00  49.644817
6  2025-06-14 06:00:00  50.157923
7  2025-06-14 07:00:00  50.258485
8  2025-06-14 08:00:00  50.020464
9  2025-06-14 09:00:00  50.995534
10 2025-06-14 10:00:00  50.661834
11 2025-06-14 11:00:00  49.824202
12 2025-06-14 12:00:00  50.048563
13 2025-06-14 13:00:00  50.080772
14 2025-06-14 14:00:00  50.307382
15 2025-06-14 15:00:00  49.691435
16 2025-06-14 16:00:00  51.595484
17 2025-06-14 17:00:00  50.992806
18 2025-06-14 18:00:00  49.384999
19 2025-06-14 19:00:00  49.449039
20 2025-06-14 20:00:00  50.112491
21 2025-06-14 21:00:00  49.561718
22 2025-06-14 22:00:00  48.555446
23 2025-06-14 23:00:00  50.950283
                  hour      value
0  2025-06-15 00:00:00  50.286802
1  2025-06-15 01:00:00  50.671154
2  2025-06-15 02:00:00  49.822571
3  2025-06-15 03:00:00  49.315217
4  2025-06-15 04:00:00  48.524785
5  2025-06-15 05:00:00  48.249567
6  2025-06-15 06:00:00  49.603560
7  2025-06-15 07:00:00  49.514786
8  2025-06-15 08:00:00  50.172439
9  2025-06-15 09:00:00  49.423943
10 2025-06-15 10:00:00  49.194150
11 2025-06-15 11:00:00  50.176292
12 2025-06-15 12:00:00  50.142569
13 2025-06-15 13:00:00  49.860078
14 2025-06-15 14:00:00  48.912837
15 2025-06-15 15:00:00  50.434689
16 2025-06-15 16:00:00  50.724006
17 2025-06-15 17:00:00  49.289026
18 2025-06-15 18:00:00  51.502391
19 2025-06-15 19:00:00  49.326719
20 2025-06-15 20:00:00  50.210237
21 2025-06-15 21:00:00  47.883384
22 2025-06-15 22:00:00  50.240238
23 2025-06-15 23:00:00  50.666740
                  hour      value
0  2025-06-16 00:00:00  51.496118
1  2025-06-16 01:00:00  50.369858
2  2025-06-16 02:00:00  50.366717
3  2025-06-16 03:00:00  50.465109
4  2025-06-16 04:00:00  49.799351
5  2025-06-16 05:00:00  48.820761
6  2025-06-16 06:00:00  49.905976
7  2025-06-16 07:00:00  50.495195
8  2025-06-16 08:00:00  50.340860
9  2025-06-16 09:00:00  49.801497
10 2025-06-16 10:00:00  50.945712
11 2025-06-16 11:00:00  50.153220
12 2025-06-16 12:00:00  50.571746
13 2025-06-16 13:00:00  49.931571
14 2025-06-16 14:00:00  48.969305
15 2025-06-16 15:00:00  51.196404
16 2025-06-16 16:00:00  49.238337
17 2025-06-16 17:00:00  50.239373
18 2025-06-16 18:00:00  50.940493
19 2025-06-16 19:00:00  51.534211
20 2025-06-16 20:00:00  51.469128
21 2025-06-16 21:00:00  50.614921
22 2025-06-16 22:00:00  50.270441
23 2025-06-16 23:00:00  50.063518
                  hour      value
0  2025-06-17 00:00:00  49.939857
1  2025-06-17 01:00:00  48.878565
2  2025-06-17 02:00:00  49.364351
3  2025-06-17 03:00:00  50.440880
4  2025-06-17 04:00:00  49.837051
5  2025-06-17 05:00:00  50.125669
6  2025-06-17 06:00:00  50.137927
7  2025-06-17 07:00:00  49.080815
8  2025-06-17 08:00:00  50.650074
9  2025-06-17 09:00:00  49.506830
10 2025-06-17 10:00:00  50.209498
11 2025-06-17 11:00:00  49.679396
12 2025-06-17 12:00:00  50.019636
13 2025-06-17 13:00:00  50.808546
14 2025-06-17 14:00:00  50.140386
15 2025-06-17 15:00:00  50.281083
16 2025-06-17 16:00:00  49.035875
17 2025-06-17 17:00:00  50.019999
18 2025-06-17 18:00:00  51.247699
19 2025-06-17 19:00:00  50.511800
20 2025-06-17 20:00:00  48.785562
21 2025-06-17 21:00:00  49.040047
22 2025-06-17 22:00:00  50.189468
23 2025-06-17 23:00:00  50.098862
                  hour      value
0  2025-06-18 00:00:00  48.795477
1  2025-06-18 01:00:00  50.438189
2  2025-06-18 02:00:00  49.660236
3  2025-06-18 03:00:00  49.947214
4  2025-06-18 04:00:00  50.347568
5  2025-06-18 05:00:00  50.241649
6  2025-06-18 06:00:00  50.016560
7  2025-06-18 07:00:00  51.235344
8  2025-06-18 08:00:00  49.800358
9  2025-06-18 09:00:00  51.039884
10 2025-06-18 10:00:00  51.178149
11 2025-06-18 11:00:00  49.814718
12 2025-06-18 12:00:00  50.518165
13 2025-06-18 13:00:00  49.336495
14 2025-06-18 14:00:00  50.470464
15 2025-06-18 15:00:00  49.160403
16 2025-06-18 16:00:00  49.533318
17 2025-06-18 17:00:00  50.910875
18 2025-06-18 18:00:00  50.638160
19 2025-06-18 19:00:00  49.616428
20 2025-06-18 20:00:00  51.138322
21 2025-06-18 21:00:00  50.214547
22 2025-06-18 22:00:00  50.404495
23 2025-06-18 23:00:00  49.349868
                  hour      value
0  2025-06-19 00:00:00  49.943267
1  2025-06-19 01:00:00  50.305419
2  2025-06-19 02:00:00  50.477656
3  2025-06-19 03:00:00  50.392943
4  2025-06-19 04:00:00  49.370428
5  2025-06-19 05:00:00  49.429105
6  2025-06-19 06:00:00  49.540423
7  2025-06-19 07:00:00  50.317137
8  2025-06-19 08:00:00  51.479681
9  2025-06-19 09:00:00  49.263893
10 2025-06-19 10:00:00  49.162786
11 2025-06-19 11:00:00  49.459270
12 2025-06-19 12:00:00  49.602494
13 2025-06-19 13:00:00  49.460388
14 2025-06-19 14:00:00  50.266725
15 2025-06-19 15:00:00  49.308526
16 2025-06-19 16:00:00  50.827411
17 2025-06-19 17:00:00  49.208360
18 2025-06-19 18:00:00  50.847100
19 2025-06-19 19:00:00  48.707643
20 2025-06-19 20:00:00  49.149141
21 2025-06-19 21:00:00  50.268045
22 2025-06-19 22:00:00  50.571936
23 2025-06-19 23:00:00  50.402817
                  hour      value
0  2025-06-20 00:00:00  50.992552
1  2025-06-20 01:00:00  49.638539
2  2025-06-20 02:00:00  49.941416
3  2025-06-20 03:00:00  51.260948
4  2025-06-20 04:00:00  48.755558
5  2025-06-20 05:00:00  48.632230
6  2025-06-20 06:00:00  50.164574
7  2025-06-20 07:00:00  48.979253
8  2025-06-20 08:00:00  50.206955
9  2025-06-20 09:00:00  50.507534
10 2025-06-20 10:00:00  50.408991
11 2025-06-20 11:00:00  50.621311
12 2025-06-20 12:00:00  50.422817
13 2025-06-20 13:00:00  48.248388
14 2025-06-20 14:00:00  49.424318
15 2025-06-20 15:00:00  50.418930
16 2025-06-20 16:00:00  50.216099
17 2025-06-20 17:00:00  49.971703
18 2025-06-20 18:00:00  49.593731
19 2025-06-20 19:00:00  50.999472
20 2025-06-20 20:00:00  49.713921
21 2025-06-20 21:00:00  49.715969
22 2025-06-20 22:00:00  49.951858
23 2025-06-20 23:00:00  48.892089
                  hour      value
0  2025-06-21 00:00:00  49.962824
1  2025-06-21 01:00:00  50.446097
2  2025-06-21 02:00:00  50.457348
3  2025-06-21 03:00:00  49.994359
4  2025-06-21 04:00:00  49.923244
5  2025-06-21 05:00:00  50.708679
6  2025-06-21 06:00:00  50.955182
7  2025-06-21 07:00:00  50.035245
8  2025-06-21 08:00:00  50.723061
9  2025-06-21 09:00:00  50.967082
10 2025-06-21 10:00:00  48.382913
11 2025-06-21 11:00:00  49.068791
12 2025-06-21 12:00:00  50.203190
13 2025-06-21 13:00:00  50.590570
14 2025-06-21 14:00:00  50.513628
15 2025-06-21 15:00:00  49.047742
16 2025-06-21 16:00:00  49.930725
17 2025-06-21 17:00:00  49.218179
18 2025-06-21 18:00:00  51.159227
19 2025-06-21 19:00:00  49.523450
20 2025-06-21 20:00:00  49.605704
21 2025-06-21 21:00:00  49.511973
22 2025-06-21 22:00:00  50.771190
23 2025-06-21 23:00:00  49.949541
                  hour      value
0  2025-06-22 00:00:00  51.061787
1  2025-06-22 01:00:00  49.862576
2  2025-06-22 02:00:00  49.024628
3  2025-06-22 03:00:00  50.371093
4  2025-06-22 04:00:00  49.343389
5  2025-06-22 05:00:00  49.668798
6  2025-06-22 06:00:00  50.725533
7  2025-06-22 07:00:00  50.652601
8  2025-06-22 08:00:00  50.155642
9  2025-06-22 09:00:00  50.606426
10 2025-06-22 10:00:00  49.308835
11 2025-06-22 11:00:00  51.068342
12 2025-06-22 12:00:00  49.934502
13 2025-06-22 13:00:00  51.163309
14 2025-06-22 14:00:00  50.284894
15 2025-06-22 15:00:00  49.571791
16 2025-06-22 16:00:00  50.965599
17 2025-06-22 17:00:00  50.561722
18 2025-06-22 18:00:00  50.129684
19 2025-06-22 19:00:00  50.095340
20 2025-06-22 20:00:00  49.818888
21 2025-06-22 21:00:00  51.118443
22 2025-06-22 22:00:00  50.861968
23 2025-06-22 23:00:00  51.192725
                  hour      value
0  2025-06-23 00:00:00  49.218772
1  2025-06-23 01:00:00  49.633432
2  2025-06-23 02:00:00  50.359531
3  2025-06-23 03:00:00  50.353822
4  2025-06-23 04:00:00  49.066488
5  2025-06-23 05:00:00  49.847175
6  2025-06-23 06:00:00  50.230905
7  2025-06-23 07:00:00  50.689900
8  2025-06-23 08:00:00  49.195122
9  2025-06-23 09:00:00  48.357011
10 2025-06-23 10:00:00  49.864534
11 2025-06-23 11:00:00  49.982067
12 2025-06-23 12:00:00  51.216449
13 2025-06-23 13:00:00  50.341042
14 2025-06-23 14:00:00  50.564482
15 2025-06-23 15:00:00  50.074456
16 2025-06-23 16:00:00  49.695900
17 2025-06-23 17:00:00  50.156978
18 2025-06-23 18:00:00  48.882582
19 2025-06-23 19:00:00  49.367401
20 2025-06-23 20:00:00  49.055174
21 2025-06-23 21:00:00  51.483354
22 2025-06-23 22:00:00  49.541196
23 2025-06-23 23:00:00  49.702837
                  hour      value
0  2025-06-24 00:00:00  50.228889
1  2025-06-24 01:00:00  50.855364
2  2025-06-24 02:00:00  49.561548
3  2025-06-24 03:00:00  49.791958
4  2025-06-24 04:00:00  49.880150
5  2025-06-24 05:00:00  50.401346
6  2025-06-24 06:00:00  51.361806
7  2025-06-24 07:00:00  48.928124
8  2025-06-24 08:00:00  52.158307
9  2025-06-24 09:00:00  49.041723
10 2025-06-24 10:00:00  50.086443
11 2025-06-24 11:00:00  49.216909

In [24]:
final_df = pd.concat(results, ignore_index=True)  
print(final_df)

                   hour      value
0   2025-06-01 00:00:00  50.485862
1   2025-06-01 01:00:00  49.942694
2   2025-06-01 02:00:00  49.536653
3   2025-06-01 03:00:00  50.151515
4   2025-06-01 04:00:00  48.806004
..                  ...        ...
715 2025-06-30 19:00:00  50.766593
716 2025-06-30 20:00:00  49.065881
717 2025-06-30 21:00:00  50.657145
718 2025-06-30 22:00:00  48.440872
719 2025-06-30 23:00:00  50.257774

[720 rows x 2 columns]

### exe3

##### קבלת נתונים ב stream היא שונה כי לא ניתן לדעת מראש מה כמות הערכים שיהיה בשעה 
#####    :ולכן נצטרך לעשות ממוצע בדרך אחרת:
##### נשמור מבנה נתונים דינמי כמו מילון עם 3 נתונים- השעה, הממוצע וכמות הערכים לשעה הזאת
##### כשנכנס נתון חדש נחלץ את השעה ונעגל אותה כלפי מטה ונבדוק אם היא קיימת כבר:
##### לכל שעה חדשה נשמור את הערך שלה ומספר ערכים שווה לאחד
##### ,כשנכנסת שעה שקיימת כבר נחשב ממוצע לפי הממוצע הקודם,
##### הערך החדש ומספר הערכים שקיימים בשעה הנוכחית, 
##### נניח שנשמור את הממוצע כ -ave , את מספר הערכים ב count , והערך החדש הוא value, הנוסחה לחישוב הממוצע החדש תהיה:
##### ave = (ave * count + value)/(count + 1)
##### ונעדכן את count = count + 1
#####
#####

### exe4

#### השוואה בין קבצי parquet לקבצי csv
##### הפורמט של paquet יעיל יותר באחסון נתונים בגלל שהוא פורמט אחסון עמודי - 
##### כל עמודה מאוחסנת כיחידה אחת
##### זאת בניגוד ל csv שהוא פורמט שורות - כל שורה מאוחסנת
##### כיחידה אחת, 
##### מכיוון שבדרך כלל מספר השורות גדול משמעותית ממספר העמודות-
##### אחסון מסוג parquet מאפשר דחיסה טובה יותר ומביאה לקבצים קטנים יותר
##### וזה תופס פחות מקום בזיכרון